const vehicles = [
  {
    id: 1,
    title: "KIA XCEED DRIVE 1.0 T-GDI",
    marca:"Kia",
    model: "Xceed",
    year: "2024",
    km: "3500",
    doors: 5,
    cilindrada: "",
    cv: "",
    type: "gasolina",
    color: "blanc",
    description:
      "Crossover compacte. Combina disseny esportiu, etiqueta ECO i motor turbo eficient de 120 CV. Ideal per ciutat i escapades.",
    price: "consultar"
  },
    {
    id: 2,
    title: "SEAT IBIZA",
    marca:"Seat",
    model: "Ibiza",
    year: "2005",
    km: "140.500",
    doors: 5,
    cilindrada: "1198",
    cv: "",
    type: "gasolina",
    color: "blanc",
    description:
      "Ideal per trajectes curts o primer cotxe. Motor fiable i manteniment econòmic.",
    price: "consultar",
  },
      {
    id: 3,
    title: "SEAT LEON 1.5 EcoTSI FR Edition",
    marca:"Seat",
    model: "Leon FR",
    year: "2005",
    km: "49.628",
    doors: 5,
    cilindrada: "",
    cv: "150",
    type: "gasolina",
    color: "blanc",
    description:
      "Estil esportiu i motor eficient. Inclou navegador integrat, fars LED, sensor de llums i control de creuer per a una conducció més còmoda i segura. Un compacte potent, ideal tant per ciutat com per carretera.",
    price: "20.100€",
  },
        {
    id: 4,
    title: "NISSAN MICRA DSG",
    marca:"Nissan",
    model: "Micra",
    year: "2010",
    km: "124.750",
    doors: 5,
    cilindrada: "1240",
    cv: "80",
    type: "gasolina",
    color: "negre",
    description:
      "Àgil i fàcil de conduir, perfecte per moure’t amb comoditat i gastar poc. Amb 5 portes i bon maleter, és ideal per a ús diari o com a primer cotxe.",
    price: "consultar",
  },
];